name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate coverage report
      env:
        NODE_ENV: test
        TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }} # Ensure this is set in your GitHub secrets
      run: |
        npm test
        npx coveralls < ./coverage/lcov.info

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2